spring:
  application:
    name: GFJC
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.223.48.82:3306/GFJC?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Zhangkuoyuan1230-9
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
GFJC:
  originalBasePath: D:/image/original/
  analyzedBasePath: D:/image/analyzed/
  originalHttpPath: localhost:8080/originalPicture/
  analyzedHttpPath: localhost:8080/analyzedPicture/
