spring:
  application:
    name: GFJC
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.109.204.138:3306/GFJC?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: Zhangkuoyuan1230-9
  redis:
    host: 101.33.242.250
    port: 6666
    database: 15
    password: 20020329@redis
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
#GFJC:
#  originalBasePath: D:/image/GF/original/
#  analyzedBasePath: D:/image/GF/analyzed/
#  repairedBasePath: D:/image/GF/repaired/
#  originalHttpPath: http://localhost:8080/originalPicture/
#  analyzedHttpPath: http://localhost:8080/analyzedPicture/
#  repairedHttpPath: http://localhost:8080/repairedPicture/
GFJC:
  originalBasePath: /home/image/GF/original/
  analyzedBasePath: /home/image/GF/analyzed/
  repairedBasePath: /home/image/GF/repaired/
  originalHttpPath: http://47.109.204.138:8080/originalPicture/
  analyzedHttpPath: http://47.109.204.138:8080/analyzedPicture/
  repairedHttpPath: http://47.109.204.138:8080/repairedPicture/